version: '3'
volumes:
  mysql_data:
  vendor_bundle:

services:
  mysql:
    image: "mysql:5.7"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    tty: true
    depends_on:
      - mysql
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/okonomiyakidb
    ports:
      -  "3000:3000"
