version: '3'
volumes:
  mysql_data:
  vendor_bundle:

services:
  db:
    image: "mysql"
    ports:
      - "3307:3306"
    # volumes:
    #   - "mysql_data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: okonomiyaki_db

  web:
    build: .
    tty: true
    depends_on:
      - db
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # volumes:
    #   - .:/okonomiyakidb
    ports:
      -  "3000:3000"
